# Generated by Django 6.1.2 on 2026-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoIMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('altura', models.FloatField(help_text='Altura em metros')),
                ('imc', models.FloatField(help_text='Valor do IMC calculado')),
                ('classificacao', models.CharField(help_text='Classificação do IMC', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cálculo de IMC',
                'verbose_name_plural': 'Cálculos de IMC',
                'ordering': ['-criado_em'],
            },
        ),
    ]
